/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentski_servis;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author domenosojnik
 */

/*
PRIJAVNA FUNKCIJA

CREATE OR REPLACE FUNCTION prijava (emailu VARCHAR(50), geslou VARCHAR(50))
RETURNS integer AS $$
DECLARE
emailx varchar;
BEGIN
SELECT e_mail INTO emailx FROM uporabniki WHERE e_mail LIKE (emailu) AND geslo LIKE (geslou);
IF (emailx IS NOT NULL)
THEN
return 1;
ELSE
return 0;
END IF;
END;
$$
LANGUAGE plpgsql;



CREATE OR REPLACE FUNCTION izpis_uporabnika (e_mailu VARCHAR(50))
RETURNS varchar(50) AS $$
DECLARE
imex varchar(50);
BEGIN
SELECT ime INTO imex FROM uporabniki WHERE e_mail LIKE (e_mailu);
RETURN imex;
END;
$$
LANGUAGE plpgsql;
*/


    

public class prijavna_stran extends javax.swing.JFrame {

    /**
     * Creates new form domaca_stran
     */
    public prijavna_stran() {
        
        initComponents();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        u_ime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        geslo = new javax.swing.JTextField();
        gumb_registracija = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Domaca_stran");
        setBackground(new java.awt.Color(204, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        u_ime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_imeActionPerformed(evt);
            }
        });

        jButton1.setText("Prijava");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel2.setText("Uporabniško geslo");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel1.setText("E-mail");

        gumb_registracija.setText("Registracija");
        gumb_registracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gumb_registracijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gumb_registracija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(geslo)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(u_ime, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(u_ime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(geslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gumb_registracija)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        String ime = u_ime.getText();
        String geslo_u = geslo.getText();
        
        String passwordToHash = geslo_u;
        String generatedPassword = null;
        try {
            // Create MessageDigest instance for MD5
            MessageDigest md = MessageDigest.getInstance("MD5");
            //Add password bytes to digest
            md.update(passwordToHash.getBytes());
            //Get the hash's bytes
            byte[] bytes = md.digest();
            //This bytes[] has bytes in decimal format;
            //Convert it to hexadecimal format
            StringBuilder sb = new StringBuilder();
            for(int i=0; i< bytes.length ;i++)
            {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
            //Get complete hashed password in hex format
            generatedPassword = sb.toString();
        }
        catch (NoSuchAlgorithmException e)
        {
            e.printStackTrace();
        }
        
        Connection con;
        Statement stavek;
        ResultSet rezultati;
        String sql = "SELECT * FROM prijava_a ('"+ ime +"', '"+ generatedPassword +"')";
        
        baza povezava = new baza();
        con = povezava.getConnection();
        
        try {
            stavek = con.createStatement();
            rezultati = stavek.executeQuery(sql);
            
            while (rezultati.next()) {
            int rezultat = rezultati.getInt(1);
            
            if(rezultat == 1)
        {
            
        Statement stavek2;
        ResultSet rezultati2;
        String sql2 = "SELECT * FROM izpis_uporabnika('"+ ime +"')";
            
            try {
            stavek2 = con.createStatement();
            
            rezultati2 = stavek2.executeQuery(sql2);
            
            
            while (rezultati2.next()) {
            String rezultat2 = rezultati2.getString(1);
            globalno.uporabnik_ime = rezultat2;
            }
            
            } catch (SQLException ex) {
            Logger.getLogger(prijavna_stran.class.getName()).log(Level.SEVERE, null, ex);
        }

            
        this.setVisible(false);
        domaca_stran_admin novo = new domaca_stran_admin();
        novo.setVisible(true);
        }
            
            
            
            // ČE NI ADMIN
            
            
            
        else
        {
            
        Statement stavek1;
        ResultSet rezultati1;
        String sql1 = "SELECT * FROM prijava ('"+ ime +"', '"+ generatedPassword +"')";
        
        
        try {
            stavek1 = con.createStatement();
            rezultati1 = stavek1.executeQuery(sql1);
            
            while (rezultati1.next()) {
            int rezultat1 = rezultati1.getInt(1);
            
            if(rezultat1 == 1)
        {
            
            Statement stavek2;
        ResultSet rezultati2;
        Statement stavek3;
        ResultSet rezultati3;
        String sql2 = "SELECT * FROM izpis_uporabnika('"+ ime +"')";
        String sql3 = "SELECT * FROM izpis_idja('"+ ime +"')";
            
            try {
            stavek2 = con.createStatement();
            
            rezultati2 = stavek2.executeQuery(sql2);
            
            stavek3 = con.createStatement();
            
            rezultati3 = stavek3.executeQuery(sql3);
            
            
            while (rezultati2.next()) {
            String rezultat2 = rezultati2.getString(1);
            globalno.uporabnik_ime = rezultat2;
            }
            
            while (rezultati3.next()) {
            int rezultat3 = rezultati3.getInt(1);
            globalno.id = rezultat3;
            }
            
            } catch (SQLException ex) {
            Logger.getLogger(prijavna_stran.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
        this.setVisible(false);
        domaca_stran novo = new domaca_stran();
        novo.setVisible(true);
        }
        else
                
        {
            JOptionPane.showMessageDialog(null,"Napačno geslo ali uporabniško ime!");
            
        }
            
            
        }
            
        } catch (SQLException ex) {
            Logger.getLogger(prijavna_stran.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(prijavna_stran.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        

        
        
  
  
    }//GEN-LAST:event_jButton1MouseClicked

    private void u_imeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_imeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_imeActionPerformed

    private void gumb_registracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gumb_registracijaActionPerformed
registracija registracija1= new registracija();
this.setVisible(false);
registracija1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_gumb_registracijaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prijavna_stran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prijavna_stran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prijavna_stran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prijavna_stran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prijavna_stran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField geslo;
    private javax.swing.JButton gumb_registracija;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField u_ime;
    // End of variables declaration//GEN-END:variables
}
