/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentski_servis;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.KeySpec;
import java.util.Arrays;
import java.util.Base64;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import java.lang.AbstractMethodError;
import java.security.MessageDigest;
import java.util.*;
import java.text.*;
import java.awt.event.WindowEvent;
import java.awt.*;
import java.awt.event.WindowListener;

/**
 *
CREATE OR REPLACE FUNCTION registracija (imeu VARCHAR(50), priimeku VARCHAR(50), geslou VARCHAR(50), t_stevilka int, kraj VARCHAR(50), epostau VARCHAR(50), rojstvo_u VARCHAR(50))
RETURNS integer AS $$
DECLARE
epostax VARCHAR;
rojstvo_u2 varchar(50);
BEGIN
rojstvo_u2 := to_date(rojstvo_u, 'DD-MM-YYYY');
SELECT e_mail INTO epostax FROM uporabniki WHERE e_mail LIKE epostau AND geslo LIKE ($2);
IF (epostax IS NULL)
THEN
INSERT INTO uporabniki (ime, priimek, e_mail, geslo, d_rojstva, t_stevilka, kraj_id) VALUES (imeu, priimeku, epostau, geslou, rojstvo_u2, t_stevilka, (SELECT id FROM kraji WHERE ime LIKE kraj))
RETURN 1;
ELSE
return 0;
END IF;
END;
$$
LANGUAGE plpgsql;
* 
* 
* 
 * @author domenosojnik
 */

public class registracija extends javax.swing.JFrame {

    /**
     * Creates new form registracija
     */
    
    private void initSelfListeners() {
    WindowListener taskStarterWindowListener = new WindowListener() {
        @Override
        public void windowOpened(WindowEvent e) {
            //Perform task here. In this case, we are simulating a startup (only once) time-consuming task that would use a worker. 
        }

        @Override
        public void windowClosing(WindowEvent e) {
            //Do nothing...Or something...You decide!
        }

        @Override
        public void windowClosed(WindowEvent e) {
            //Do nothing...Or drink coffee...NVM; always drink coffee!
        }

        @Override
        public void windowIconified(WindowEvent e) {
            //Do nothing...Or do EVERYTHING!
        }
        
     @Override
        public void windowDeiconified(WindowEvent e) {
            //Do nothing...Or break the law...
        }

        @Override
        public void windowActivated(WindowEvent e) {
            //Do nothing...Procrastinate like me!
        }

        @Override
        public void windowDeactivated(WindowEvent e) {
            //Do nothing...And please don't notice I have way too much free time today...
        }
    };

    //Here is where the magic happens! We make (a listener within) the frame start listening to the frame's own events!
    
}
    
    
    
    
    
    public registracija() {
        initComponents();     
        initSelfListeners();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ime_uporabnika = new javax.swing.JTextField();
        priimek_uporabnika = new javax.swing.JTextField();
        eposta_uporabnika = new javax.swing.JTextField();
        dan_rojstva = new javax.swing.JTextField();
        t_stevilka_uporabnika = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kraj_uporabnika = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        mesec_rojstva = new javax.swing.JTextField();
        leto_rojstva = new javax.swing.JTextField();
        geslo_uporabnika = new javax.swing.JPasswordField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        eposta_uporabnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eposta_uporabnikaActionPerformed(evt);
            }
        });

        dan_rojstva.setText("Dan");

        jLabel1.setText("Ime");

        jLabel2.setText("Priimek");

        jLabel3.setText("E-pošta");

        jLabel4.setText("Kraj bivanja");

        jLabel5.setText("Telefonska številka");

        jLabel6.setText("Geslo");

        jLabel7.setText("Datum rojstva");

        jButton1.setText("Registracija");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("Obrazec za registracijo");

        mesec_rojstva.setText("Mesec");

        leto_rojstva.setText("Leto");

        geslo_uporabnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geslo_uporabnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(87, 87, 87))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(49, 49, 49))
                            .addComponent(kraj_uporabnika, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(300, 300, 300))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(geslo_uporabnika, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priimek_uporabnika, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(153, 153, 153))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(180, 180, 180))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(156, 156, 156))
                            .addComponent(eposta_uporabnika, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ime_uporabnika, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_stevilka_uporabnika, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(dan_rojstva, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesec_rojstva, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(leto_rojstva, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(219, 219, 219))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ime_uporabnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priimek_uporabnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eposta_uporabnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kraj_uporabnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_stevilka_uporabnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dan_rojstva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesec_rojstva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leto_rojstva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geslo_uporabnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eposta_uporabnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eposta_uporabnikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eposta_uporabnikaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if ( ime_uporabnika.getText().trim().length() == 0 
                 || priimek_uporabnika.getText().trim().length() == 0 
                
                 || eposta_uporabnika.getText().trim().length() == 0
                 || t_stevilka_uporabnika.getText().trim().length() == 0)          
    {
        JOptionPane.showMessageDialog(null,"Izpolni podatke pravilno.");
    }
         
    else
         {
        //izpis krajev v combobox
        Connection con;
        baza povezava = new baza();
        con = povezava.getConnection();

        Object varName = (Object)kraj_uporabnika.getSelectedItem();
String value = kraj_uporabnika.getSelectedItem().toString();
        
        String ime = ime_uporabnika.getText();
        String priimek = priimek_uporabnika.getText();
        String geslo = new String(geslo_uporabnika.getPassword());
        String celoten_datum = leto_rojstva.getText() + "-" + mesec_rojstva.getText() + "-" + dan_rojstva.getText();
        String stevilka = t_stevilka_uporabnika.getText();
        String kraj = value;
        String mail = eposta_uporabnika.getText();
        
        
        
       String passwordToHash = geslo;
        String generatedPassword = null;
        try {
            // Create MessageDigest instance for MD5
            MessageDigest md = MessageDigest.getInstance("MD5");
            //Add password bytes to digest
            md.update(passwordToHash.getBytes());
            //Get the hash's bytes
            byte[] bytes = md.digest();
            //This bytes[] has bytes in decimal format;
            //Convert it to hexadecimal format
            StringBuilder sb = new StringBuilder();
            for(int i=0; i< bytes.length ;i++)
            {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
            //Get complete hashed password in hex format
            generatedPassword = sb.toString();
        }
        catch (NoSuchAlgorithmException e)
        {
            e.printStackTrace();
        }
        
        System.out.println(generatedPassword);
        
        
        
        Statement stavek;
        ResultSet rezultati;
        String sql = "SELECT * FROM registracija ('"+ ime +"', '"+ priimek +"', '"+ generatedPassword +"', '"+ stevilka +"', 'Velenje', '"+ mail +"', '"+ celoten_datum +"') LIMIT 1";
        
        
        try {
            stavek = con.createStatement();
            rezultati = stavek.executeQuery(sql);
            
            while (rezultati.next()) {
            int rezultat = rezultati.getInt(1);
            
            if(rezultat == 1)
        {
        JOptionPane.showMessageDialog(null,"Uspešna registracija!");
        this.setVisible(false);
        prijavna_stran prijava = new prijavna_stran();
        prijava.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Email je ze v uporabi.");
            
        }
            
            con.close();
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(prijavna_stran.class.getName()).log(Level.SEVERE, null, ex);
        
        
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Connection con;
        baza povezava = new baza();
        con = povezava.getConnection();
        
        try {
             Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select * from izpis_krajev()");
        while (rs.next()) {
            String pat = rs.getString("ime_kraja");
            
            kraj_uporabnika.addItem(pat);
        }
        con.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(registracija.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void geslo_uporabnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geslo_uporabnikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geslo_uporabnikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registracija().setVisible(true);
            }
        });
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dan_rojstva;
    private javax.swing.JTextField eposta_uporabnika;
    private javax.swing.JPasswordField geslo_uporabnika;
    private javax.swing.JTextField ime_uporabnika;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> kraj_uporabnika;
    private javax.swing.JTextField leto_rojstva;
    private javax.swing.JTextField mesec_rojstva;
    private javax.swing.JTextField priimek_uporabnika;
    private javax.swing.JTextField t_stevilka_uporabnika;
    // End of variables declaration//GEN-END:variables
}
